### ISSUE TITLE
what happen when print unexpected EOF ?

### ISSUE THREAD

**Issue by Michaelmilk** [txthinking/zoro#10]
### Prerequisites

* [ ] Did you search in [issues](https://github.com/txthinking/mr2/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.

### Environment

* Mr.2 Version:
* Server Operating System:Win10
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:Win10
* Client Operating System Version:
* Client Operation System Language:

### Possible Solution
![image](https://user-images.githubusercontent.com/6982589/57668828-3c913800-75f8-11e9-9f4f-ec479a6befe9.png)

Is there some illegal chars ?

**Comment by txthinking** [comment]
Can you provide specific steps?

**Comment by Michaelmilk** [comment]
sorry  i can't repro it.  let's close it now
