### ISSUE TITLE
The version of mr2 20191224 can't run. It says "flag provided but not defined: -P"

### ISSUE THREAD

**Issue by m2acgi** [txthinking/zoro#17]
### Prerequisites

- [x] Did you search in [issues](https://github.com/txthinking/mr2/issues)?
- [x]  Are you running the latest version?
- [x]  I will write this according to this template.

### Environment

* Mr.2 Version: 20191224
* Server Operating System: CentOS 8
* Server Operating System Version: CentOS 8.0.1905 amd64
* Server Operation System Language: en_US
* Client Operating System: 
* Client Operating System Version:
* Client Operation System Language:

### Expected Behavior
Running without error.

### Current Behavior
After run the command `mr2 server -l :9999 -P '5678 password' -P '6789 password1'`, it says `2019/12/25 01:23:15 flag provided but not defined: -P`

### Steps to Reproduce

1. On the server to run the command `mr2 server -l :9999 -P '5678 password' -P '6789 password1`
2.
3.

**Comment by txthinking** [comment]
Please try v20200102

**Comment by m2acgi** [comment]
v20200102 works like a charm. thx.
