### ISSUE TITLE
Incompatible with Go 1.23 because of old golang.org/x/net

### ISSUE THREAD

**Issue by stefanb** [txthinking/zoro#29]
While testing Go 1.23 rc2 in 
* https://github.com/Homebrew/homebrew-core/pull/175310
 
there was an error:
````
  # github.com/txthinking/zoro/cli/zoro
  link: golang.org/x/net/internal/socket: invalid reference to syscall.recvmsg
````

Go 1.23 no longer allows `//go:linkname * runtime.*` link instructioins, see 
* https://tip.golang.org/doc/go1.23#linker
* https://github.com/golang/go/issues/67401

It is used in the referenced ancient `golang.org/x/net` module:
https://github.com/txthinking/zoro/blob/940e11004d63337dfabd6d50ebe39c98a100229f/go.mod#L18

`golang.org/x/net` should be updated to a recent version for Go 1.23 compatibility.

**Comment by txthinking** [comment]
I think you can create release for this repository now, no need care binaries.  I'm currently spending my time making youtube videos. Thanks for your time.

**Comment by stefanb** [comment]
Released [v20240828](https://github.com/txthinking/zoro/releases/tag/v20240828).
