### ISSUE TITLE
在ubuntu上服务端运行不起来

### ISSUE THREAD

**Issue by blackzw** [txthinking/zoro#3]
### Prerequisites

* [x] Did you search in [issues](https://github.com/txthinking/mr2/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.

### Environment

* Mr.2 Version: latest
* Server Operating System: ubuntu
* Server Operating System Version: 18.04
* Server Operation System Language: english
* Client Operating System:  
* Client Operating System Version:
* Client Operation System Language:

### Expected Behavior
启动mr2的服务端
### Current Behavior
执行指令：./mr2_linux_arm64 server -l :9999 -p password
### Detailed Description
显示：
-bash: ./mr2_linux_arm64: cannot execute binary file: Exec format error

**Comment by txthinking** [comment]
你下载的是arm架构版本.
你可能应该下载这个:
https://github.com/txthinking/mr2/releases/download/v20190506/mr2

**Comment by blackzw** [comment]
下载后执行./mr server -l :18989 -p password
之后没有任何提示，停在那里了。

**Comment by txthinking** [comment]
这就正常的. 代表已经正在运行.
如果你想后台运行:
$ nohup ./mr2 server -l :18989 -p password &
停止:
$ killall mr2
