### ISSUE TITLE
在Win10上如何使用呢？

### ISSUE THREAD

**Issue by LyleLaii** [txthinking/zoro#4]
打开exe后没有其他反应，在命令行或者powershell里输入mr2无效

**Comment by LyleLaii** [comment]
在exe文件目录下，通过命令行执行mr2文件可以运行了

**Comment by suntong** [comment]
> verybid:
> 老大，brook可以加一个IP层的端口转发功能吗?raw socket那种，或者直接tap/tun走出去，不要中间建立两套tcp连接那种，就像iptables那样的。
> ￼
> [3:34:40 AM]Cloud:admin
> 非linux不熟悉(好像也没有?) linux就是对接内核层的netfilter, 也就再造一个iptables了
> 

@txthinking, is mr2 using the same mechanism under both Linux and Windows, as described above? 

Any problem I'm connecting Linux and Windows using mr2?
