### ISSUE TITLE
有大概原理中文版本吗

### ISSUE THREAD

**Issue by lucasjinreal** [txthinking/zoro#5]
外网机器远程本地机器，这个原理是如何实现的呢

**Comment by txthinking** [comment]
简单的说就是中继.
外网<---TCP/UDP--->服务器<---TCP/UDP--->本地

**Comment by lucasjinreal** [comment]
@txthinking  类似于zerotier吗？服务器运行mr2，一个本地机器人运行一个mr2 client，然后这两台机器可以通过外网互相访问？

**Comment by txthinking** [comment]
部分目的相同, 但是mr2并不组网.

**Comment by lucasjinreal** [comment]
没看懂
